'use client';
import type { FieldErrors, UseFormRegister } from 'react-hook-form';
import type { EmergencyProfileInput } from '@/lib/emergency/schema';

type Props = { register: UseFormRegister<EmergencyProfileInput>; errors: FieldErrors<EmergencyProfileInput> };
function Input({ name, label, register, errors, as = 'input', ...props }: Props & { name: keyof EmergencyProfileInput; label: string; as?: 'input' | 'textarea' | 'select'; placeholder?: string; type?: string; children?: React.ReactNode }) {
  const id = `field-${name}`;
  return <label className="label" htmlFor={id}>{label}{as === 'textarea' ? <textarea id={id} className="field min-h-28" {...register(name)} {...props} /> : as === 'select' ? <select id={id} className="field" {...register(name)}>{props.children}</select> : <input id={id} className="field" {...register(name)} {...props} />}{errors[name]?.message ? <span className="helper-error">{String(errors[name]?.message)}</span> : null}</label>;
}
export function PersonSection(props: Props) { return <Section title="Perfil del piloto" eyebrow="Identidad pública"><div className="grid gap-4 md:grid-cols-2"><Input name="alias" label="Alias recomendado" placeholder="Ej. AREIVAN" {...props} /><Input name="name" label="Nombre" placeholder="Ej. Areivan Angeles" {...props} /><Input name="phone" label="Teléfono" type="tel" placeholder="Ej. +52 55 ..." {...props} /><Input name="baseUrl" label="Base URL" placeholder="https://tudominio.com" {...props} /></div></Section>; }
export function MedicalSection(props: Props) { return <Section title="Datos médicos" eyebrow="Crítico"><div className="grid gap-4 md:grid-cols-2"><Input name="blood" label="Tipo de sangre" as="select" {...props}><option value="">(opcional)</option>{['O+','O-','A+','A-','B+','B-','AB+','AB-'].map((b) => <option key={b}>{b}</option>)}</Input><Input name="allergies" label="Alergias" placeholder="Penicilina, mariscos" {...props} /><Input name="medical" label="Condiciones médicas" placeholder="Asma, diabetes" {...props} /><Input name="notes" label="Notas" as="textarea" placeholder="Si estoy inconsciente..." {...props} /></div></Section>; }
export function EmergencyContactSection(props: Props) { return <Section title="Contacto de emergencia" eyebrow="A quién llamar"><Input name="contact" label="Nombre + teléfono" placeholder="Ej. Ana +52 55 ..." {...props} /></Section>; }
export function MotorcycleSection(props: Props) { return <Section title="Moto" eyebrow="Identificación"><div className="grid gap-4 md:grid-cols-2"><Input name="bike" label="Marca / Modelo" placeholder="CFMOTO 675 SR-R" {...props} /><Input name="plate" label="Placas" placeholder="ABC-12-34" {...props} /><Input name="color" label="Color" placeholder="Negro / morado" {...props} /><Input name="policy" label="Póliza / aseguradora" placeholder="Qualitas / #123" {...props} /><Input name="extra" label="Extra" placeholder="VIN, seguro, etc." {...props} /></div></Section>; }
export function QRSettingsSection() { return <div className="rounded-3xl border border-apex-amber/25 bg-apex-amber/10 p-4 text-sm leading-6 text-amber-100">Compartí solo los datos que aceptás exponer. Esto no reemplaza identificación oficial, seguro ni atención médica profesional.</div>; }
function Section({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) { return <section className="glass-card rounded-4xl p-5 transition duration-200 ease-premium hover:-translate-y-0.5"><div className="mb-4 flex items-start justify-between gap-4"><h3 className="text-lg font-black">{title}</h3><span className="text-xs font-bold uppercase tracking-[.14em] text-apex-cyan">{eyebrow}</span></div>{children}</section>; }
